config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  root :to => "posts#index"

  resources :posts
  resources :comments
  resources :users

  patch 'comments/validate_comment/:id' => 'comments#validate_comment'
  post 'posts/search' => 'posts#search'
  get 'auth/login' => 'auth#login'
  get '/auth/:provider/callback' => 'authentications#create'
  post '/auth/:provider/callback' => 'authentications#create'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authorize, :except => [:index, :new, :create]
  before_action :set_comment, :only => [:show, :edit, :update, :destroy, :validate_comment]

  # GET /comments
  # GET /comments.json
  def index
    params.permit(:post_id)
    if params[:post_id]
      if current_user && current_user.is_admin?
        @comments = Comment.where(:post_id => params[:post_id]).includes(:user)
      else
        @comments = Comment.where(:post_id => params[:post_id], :is_validated => true).includes(:user)
      end
    end
  end

  def validate_comment
    @comment.is_validated = true
    @comment.save
    flash[:notice] = "Commentaire validé."
    redirect_to request.referer
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    if current_user
      @comment = Comment.new
      @comment.post_id = params[:post_id]
    else
      flash[:notice] = "Vous devez être connecté pour poster un commentaire."
      redirect_to :controller => :posts, :action => :index
    end
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.is_validated = false
    respond_to do |format|
      if @comment.save
        flash[:notice] = "Votre commentaire a été posté. Il sera visible lorsque qu'il aura été validé."
        format.html { redirect_to :controller => :posts, :action => :index }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :post_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% devise_error_messages! %>
  <%= f.hidden_field :post_id, :value => @comment.post_id %>

  <div><%= f.label "Commentaire : " %><br />
    <%= f.text_field :content%>
  </div>

  <br/>

  <div><%= f.submit "Envoyer" %></div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Liste des commentaires</h1>
<br/><br/>
<% if @comments.length == 0 %>
  Pas de commentaire.
<% else %>
  <% @comments.each do |comment| %>
    <%= comment.user.email %> a écrit :
    <br><br>
    "<%= comment.content %>"
    <% if !comment.is_validated? && current_user && current_user.is_admin? %>
      <br/>
      <%= form_for(comment, :url => {:action => :validate_comment, :id => comment.id ,:controller => :comments}) do |f| %>
        <%= f.submit "Valider le commentaire" %>
      <% end %>
    <% end %>
    <br/><br/><br/>
  <% end %>
<%end%>
<br>

app/views/comments/new.html.erb
<h1>Nouveau commentaire</h1>

<%= render 'form' %>
<br/>
<%= link_to 'Retour', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>